version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - study-group-db:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    tty: true
    stdin_open: true
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/study_group
    ports:
      - "3000:3000"
    links:
      - db
    env_file: development.env
  
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
      
volumes:
  study-group-db: